name_exp: celeba_base
dataset: celeba
train_w_score: false
workers: 16
batch_size: 128
image_size: 64
lr: 0.00008
ngpu: 1
optimizer: lion
train_config:
  _target_:  utils.Train_config_DSB
  z_dim: 0
  generator_type: unet
  consistency: True
  diffusion_type: var_exp
  sigma_min: 0.002
  sigma_max: 80
  sigma_data: 0.5
  s0: 10
  s1: 1280
  ema_decay: 0.9999
  ema_start: 0
  n_train_steps: 150000
  generator_induced_traj: False
  generator_induced_traj_ema: False
generator:
  _target_: edm_networks.ConsistencyPrecond
  img_resolution: 64
  img_channels: 3
  sigma_min: 0.002
  sigma_max: 80
  sigma_data: 0.5
  model_channels: 128
  dropout: [0.0,0.0,0.2,0.2]
  num_blocks: [3,3,4,5]
  embedding_type: positional
  augment_dim: 0
  channel_mult: [1,2,2,2]