name_exp: cifar10_GC_mix50
dataset: cifar10
train_w_score: false
workers: 16
batch_size: 512
image_size: 32
lr: 0.0001
ngpu: 1
optimizer: lion
train_config:
  _target_:  utils.Train_config
  n_train_steps: 100000
  diffusion_type: var_exp
  sigma_min: 0.002
  sigma_max: 80
  sigma_data: 0.5
  s0: 10
  s1: 1280
  ema_decay: 0.9999
  ema_start: 0
  generator_induced_traj: True
  generator_induced_traj_ema: True
  start_generator_induced_traj: 0
  mix_gen_induced_traj: 0.5
generator:
  _target_: edm_networks.ConsistencyPrecond
  img_resolution: 32
  img_channels: 3
  sigma_min: 0.002
  sigma_max: 80
  sigma_data: 0.5
  model_channels: 128
  dropout: 0.
  num_blocks: 3
  embedding_type: positional
  augment_dim: 0
  channel_mult: [1,2,2]
