name_exp: imagenet_Base
dataset: imagenet
train_w_score: false
workers: 16
batch_size: 64
image_size: 32
lr: 0.0001
ngpu: 1
optimizer: lion
train_config:
  _target_:  utils.Train_config
  diffusion_type: interpolation
  n_train_steps: 150000
  sigma_min: 0.002
  sigma_max: 1
  sigma_data: 0.5
  s0: 10
  s1: 1280
  ema_decay: 0.9999
  ema_start: 20000
generator:
  _target_: edm_networks.ConsistencyPrecond
  img_resolution: 32
  img_channels: 3
  sigma_min: 0.002
  sigma_max: 1
  sigma_data: 0.5
  model_channels: 128
  dropout: [0.1,0.3,0.3]
  num_blocks: [4,5,7]
  embedding_type: positional
  augment_dim: 0
  channel_mult: [1,1,2]
  attn_resolutions: [16]